### ISSUE TITLE
Maybe find an alternative and close this plugin

### ISSUE THREAD

**Issue by marekdedic** [skaut/skaut-bazar#39]

**Comment by kalich5** [comment]
I searched, but nothing is that simple.

**Comment by marekdedic** [comment]
Investigating https://wpadverts.com/

**Comment by kalich5** [comment]
Alternativní plugin vyzkoušen, na to co je potřeba si myslím v pohodě stačí. Takže bychom měli udělat hlášku, vydat aktualizaci a na konci roku tenhle plugin za wordpress.org uzavřu.

**Comment by kalich5** [comment]
https://cs.wordpress.org/plugins/wpadverts/
